//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Omega
{
    using System;
    using System.Collections.Generic;
    
    public partial class PredloziKolegu
    {
        public int ID { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Email { get; set; }
        public string TelefonskiBroj { get; set; }
        public string Adresa { get; set; }
        public string DrustvenaMreza { get; set; }
        public string PismoZamolbe { get; set; }
        public byte[] Zivotopis { get; set; }
        public int IDTipPrijave { get; set; }
        public int IDRadnoMjesto { get; set; }
        public int IDNatjecaj { get; set; }
    
        public virtual Natjecaj Natjecaj { get; set; }
        public virtual RadnoMjesto RadnoMjesto { get; set; }
        public virtual TipPrijave TipPrijave { get; set; }
    }
}
