//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Omega
{
    using System;
    using System.Collections.Generic;
    
    public partial class UputeZaRad
    {
        public int UputeZaRadID { get; set; }
        public string Naziv { get; set; }
        public byte[] URL { get; set; }
        public System.DateTime Datum { get; set; }
        public string Objavio { get; set; }
    }
}
